version = 1

[envs.lazygit]
channels = ["conda-forge"]
dependencies = { lazygit = "*" }
exposed = { lazygit = "lazygit" }

[envs.git-delta]
channels = ["conda-forge"]
dependencies = { git-delta = "*" }
exposed = { delta = "delta" }

[envs.difftastic]
channels = ["conda-forge"]
dependencies = { difftastic = "*" }
exposed = { difft = "difft" }

[envs.texlab]
channels = ["conda-forge"]
dependencies = { texlab = "*" }
exposed = { texlab = "texlab" }

[envs.uv]
channels = ["conda-forge"]
dependencies = { uv = "*" }
exposed = { uv = "uv", uvx = "uvx" }

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

# [envs.pylyzer]
# channels = ["conda-forge"]
# dependencies = { pylyzer = "*" }
# exposed = { pylyzer = "pylyzer" }

# [envs.basedpyright]
# channels = ["conda-forge"]
# dependencies = { basedpyright = "*" }
# exposed = { basedpyright = "basedpyright", basedpyright-langserver = "basedpyright-langserver" }

[envs.grayskull]
channels = ["conda-forge"]
dependencies = { grayskull = "*", conda-recipe-manager = "*" }
exposed = { grayskull = "grayskull", greyskull = "greyskull", conda-grayskull = "conda-grayskull", conda-greyskull = "conda-greyskull" }

[envs.proselint]
channels = ["conda-forge"]
dependencies = { proselint = "*" }
exposed = { proselint = "proselint" }

[envs.feedrattler]
channels = ["conda-forge"]
dependencies = { feedrattler = "*" }
exposed = { feedrattler = "feedrattler" }

[envs.vitables]
channels = ["conda-forge"]
dependencies = { vitables = "*", pyside6 = "*" }
exposed = { vitables = "vitables" }

[envs.tex-fmt]
channels = ["conda-forge"]
dependencies = { tex-fmt = "*" }
exposed = { tex-fmt = "tex-fmt" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.tmux]
channels = ["conda-forge"]
dependencies = { tmux = "*" }
exposed = { tmux = "tmux" }

[envs.latexmk]
channels = ["conda-forge"]
dependencies = { latexmk = "*" }
exposed = { latexmk = "latexmk" }

[envs.latexdiff]
channels = ["conda-forge"]
dependencies = { latexdiff = "*" }
exposed = { latexdiff = "latexdiff", latexdiff-vc = "latexdiff-vc" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.universal-ctags]
channels = ["conda-forge"]
dependencies = { universal-ctags = "*" }
exposed = { ctags = "ctags", optscript = "optscript", readtags = "readtags" }

[envs.lua-language-server]
channels = ["conda-forge"]
dependencies = { lua-language-server = "*" }
exposed = { lua-language-server = "lua-language-server" }

[envs.ty]
channels = ["conda-forge", "conda-forge/label/ty_alpha"]
# dependencies = { ty = ">=0.0.1a19,<0.0.1a20" }
dependencies = { ty = "*" }
exposed = { ty = "ty" }

[envs.topgrade]
channels = ["conda-forge"]
dependencies = { topgrade = "*" }
exposed = { topgrade = "topgrade" }

[envs.pyrefly]
channels = ["conda-forge"]
dependencies = { pyrefly = "*" }
exposed = { pyrefly = "pyrefly" }

[envs.nvim]
channels = ["conda-forge"]
dependencies = { nvim = "*" }
exposed = { nvim = "nvim" }

# [envs.python-lsp-server-base]
# channels = ["conda-forge"]
# dependencies = { python-lsp-server-base = "*", pylsp-rope = "*" }
# exposed = { pylsp = "pylsp" }

# [envs.jedi-language-server]
# channels = ["conda-forge"]
# dependencies = { jedi-language-server = "*" }
# exposed = { jedi-language-server = "jedi-language-server" }
