[project]
authors = ["Jan Robert Schmidt <jan_robert.schmidt@tu-dresden.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "CPG_stable"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
numba = ">=0.62.1,<0.63"
numpy = ">=2.3.3,<3"
scipy = ">=1.16.2,<2"
matplotlib = ">=3.10.6,<4"
cython = ">=3.1.4,<4"
mpmath = ">=1.3.0,<2"
gmpy2 = ">=2.2.1,<3"
h5py = ">=3.14.0,<4"
pytables = ">=3.10.2,<4"
ipython = ">=9.6.0,<10"
mayavi = { version = ">=4.8.3,<5", build = "pyside6_*" }
mongoengine = ">=0.29.1,<0.30"
sympy = ">=1.14.0,<2"
swig = ">=4.3.1,<5"
tqdm = ">=4.67.1,<5"
wxpython = ">=4.2.3,<5"
scikit-learn = ">=1.7.2,<2"
coverage = ">=7.10.7,<8"
networkx = ">=3.5,<4"
pytest = ">=8.4.2,<9"
pytest-cov = ">=7.0.0,<8"
pyx = ">=0.16,<0.17"
jupyterlab = ">=4.4.9,<5"
ipywidgets = ">=8.1.7,<9"
jupyterlab-lsp = ">=5.2.0,<6"
pandas = ">=2.3.3,<3"
shapely = ">=2.1.2,<3"
jupytext = ">=1.17.3,<2"
line_profiler = ">=5.0.0,<6"
fast-histogram = ">=0.14,<0.15"
filelock = ">=3.19.1,<4"
qtpy = ">=2.4.3,<3"
pypdf2 = ">=3.0.1,<4"
meson = ">=1.9.0,<2"
scipy-stubs = ">=1.16.2.0,<2"
cxroots = ">=3.0.2,<4"
pynose = ">=1.5.5,<2"
python-lsp-server-base = ">=1.13.1,<2"
pylsp-rope = ">=0.1.17,<0.2"
jax = ">=0.7.1,<0.8"

[target.linux-64.dependencies]
qt6-wayland = ">=6.9.2,<7"
